version: "3.9"

services:

  backend:
    container_name: task_manager_back
    image: task_manager_instance
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.api.v1.endpoints:app --host 0.0.0.0 --port 8000 --reload --log-level debug
      "

  db:
    env_file:
      - .env
    container_name: task_manager_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_HOST: ${DB_NAME_SERVICE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_EXIT_PORT}:5432"